# Generated by Django 3.1.7 on 2021-04-05 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=50)),
                ('is_done', models.BooleanField(default=False)),
                ('details', models.TextField()),
                ('deadline', models.TimeField()),
            ],
        ),
    ]
