# Generated by Django 3.1.7 on 2021-04-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_auto_20210405_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.CharField(max_length=50),
        ),
    ]
