# Generated by Django 3.1.7 on 2021-04-05 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_auto_20210405_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline']},
        ),
    ]
